/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animal;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class jftv3squamata extends javax.swing.JFrame {
    String c;
    String v2;
    animalBR objbr = new animalBR();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jftv2reptil.class.getName());
    
    
    
    public jftv3squamata(String vv2) {
        v2 = vv2;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuerPata = new javax.swing.JCheckBox();
        vene = new javax.swing.JCheckBox();
        trepAR = new javax.swing.JCheckBox();
        tercO = new javax.swing.JCheckBox();
        bifos = new javax.swing.JCheckBox();
        encadenar = new javax.swing.JButton();
        siga = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        vertes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cuerPata.setText("Cuerpo con patas");
        cuerPata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuerPataActionPerformed(evt);
            }
        });

        vene.setText("Veneno");

        trepAR.setText("Trepa árboles");

        tercO.setText("Tercer ojo parietal");

        bifos.setText("Lengua bífida");

        encadenar.setText("Encadenar");
        encadenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encadenarActionPerformed(evt);
            }
        });

        siga.setText("Siguiente");
        siga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigaActionPerformed(evt);
            }
        });

        jLabel1.setText("Vertebrado 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encadenar)
                    .addComponent(cuerPata)
                    .addComponent(vene)
                    .addComponent(trepAR)
                    .addComponent(tercO)
                    .addComponent(bifos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(siga)
                    .addComponent(jLabel1)
                    .addComponent(vertes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuerPata)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vene)
                    .addComponent(vertes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trepAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tercO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bifos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encadenar)
                    .addComponent(siga))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuerPataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuerPataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuerPataActionPerformed

    private void encadenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encadenarActionPerformed
        String cp = "",vn = "", ta = "", top = "", lb = "";
        if (cuerPata.isSelected()) cp = "si";
        else  cp = "no";
        
        if (vene.isSelected()) vn = "si";
        else  vn = "no";
        
        if (trepAR.isSelected()) ta = "si";
        else  ta = "no";
        
        if (tercO.isSelected()) top = "si";
        else  top = "no";
        
        if (bifos.isSelected()) lb = "si";
        else  lb = "no";
        
        System.out.println("\nCuerpo con patas=" + cp + "\nVeneno=" + vn
                + "\nTrepa arboles=" + ta + "\nOjo parietal=" + top+
                "\nLengua bifida= "+lb);
        c = objbr.getV3(v2, cp, vn, ta, top, lb);
        System.out.println("V3=" + c);
        vertes.setText(c);
    }//GEN-LAST:event_encadenarActionPerformed

    private void sigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigaActionPerformed
        try{
            if (c.equals("ANGUIDAE")) {
                jftvanguidae ang = new jftvanguidae(c);
                ang.setVisible(true);
            }
            else if (c.equals("ELAPIDAE")){
                v3ela ela = new v3ela(c);
                ela.setVisible(true);
            }
            else if (c.equals("IGUANIDAE")){
                v4Igua igua = new v4Igua(c);
                igua.setVisible(true);
            }
        }
        catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this,
                    "Verifica las entradas", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sigaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bifos;
    private javax.swing.JCheckBox cuerPata;
    private javax.swing.JButton encadenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton siga;
    private javax.swing.JCheckBox tercO;
    private javax.swing.JCheckBox trepAR;
    private javax.swing.JCheckBox vene;
    private javax.swing.JLabel vertes;
    // End of variables declaration//GEN-END:variables
}
