/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animal;

import javax.swing.JOptionPane;

/**
 *
 * @author mauri
 */
public class jftv2reptil extends javax.swing.JFrame {
    String c;
    String v1;
    animalBR objbr = new animalBR();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jftv2reptil.class.getName());

    /**
     * Creates new form jftv2reptil
     */
    public jftv2reptil(String vv1) {
        v1 = vv1;
        initComponents();
        reptil.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        muda = new javax.swing.JCheckBox();
        capa = new javax.swing.JCheckBox();
        cola = new javax.swing.JCheckBox();
        cabeza = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        reptil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        muda.setText("Muda piel");
        muda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudaActionPerformed(evt);
            }
        });

        capa.setText("caparazon");

        cola.setText("Cola para nadar");

        cabeza.setText("Cabeza de pico");

        jButton1.setText("Encadenar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Siguiente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Vertebrado 2");

        reptil.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cola)
                        .addComponent(muda, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(capa, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cabeza, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reptil, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muda)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capa)
                    .addComponent(reptil))
                .addGap(27, 27, 27)
                .addComponent(cola)
                .addGap(29, 29, 29)
                .addComponent(cabeza)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mudaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String mp = "", cpzn = "", cn = "", cp = "";
        if (muda.isSelected()) {
            mp = "si";
        } else {
            mp = "no";
        }
        if (capa.isSelected()) {
            cpzn = "si";
        } else {
            cpzn = "no";
        }
        if (cola.isSelected()) {
            cn = "si";
        } else {
            cn = "no";
        }
        if (cabeza.isSelected()) {
            cp = "si";
        } else {
            cp = "no";
        }
        System.out.println("\nMuda piel=" + mp + "\nCaparazon="
                + cpzn + "\nCola para nadar=" + cn + "\nCabeza de pico=" + cp);
        c = objbr.getVertebrado2Reptil(v1,mp, cpzn, cn, cp);
        System.out.println("V2=" + c);
        reptil.setText(c);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            if (c.equals("SQUAMATA")) {
                jftv3squamata squa = new jftv3squamata(c);
                squa.setVisible(true);
            }
            else if (c.equals("TESTUDINES")){
                v3Testu testu = new v3Testu(c);
                testu.setVisible(true);
            }
        }
        catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this,
                    "Verifica las entradas", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cabeza;
    private javax.swing.JCheckBox capa;
    private javax.swing.JCheckBox cola;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox muda;
    private javax.swing.JLabel reptil;
    // End of variables declaration//GEN-END:variables
}
